<?php

namespace TicketsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilecsvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilecsvRepository extends EntityRepository
{
}
