# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    db.class: TicketsBundle\Db\Db

    database.db1.dsn: mysql:host=localhost;dbname=tickets_appels
    database.db1.username: root
    database.db1.password: null

    database.db2.dsn: pgsql:host=127.0.0.1;port=5432;dbname=testdb
    database.db2.username: username
    database.db2.password: password

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    db1:
        class: %db.class%
        calls:
          - [setDsn, [%database.db1.dsn%]]
          - [setUsername, [%database.db1.username%]]
          - [setPassword, [%database.db1.password%]]
    db2:
        class: %db.class%
        calls:
          - [setDsn, [%database.db2.dsn%]]
          - [setUsername, [%database.db2.username%]]
          - [setPassword, [%database.db2.password%]]


